name: CI - Tests & Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Run Django tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: messaging_db
          DB_USER: root
          DB_PASSWORD: root
        run: |
          cd messaging_app
          python manage.py migrate
          pytest --ds=messaging_app.settings --junitxml=pytest-report.xml --cov=.

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report.xml

      - name: Run flake8 Linting
        run: |
          pip install flake8
          flake8 messaging_app --max-line-length=88 --statistics --count

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
